# Generated by Django 6.0.2 on 2026-02-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_medicalreport_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientuser',
            name='patient_id',
            field=models.CharField(editable=False, max_length=9, unique=True),
        ),
    ]
