# Generated by Django 6.0.2 on 2026-02-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patientuser_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientuser',
            name='patient_id',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
