# Generated by Django 6.0.2 on 2026-02-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_patientuser_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(max_length=20),
        ),
    ]
