# Generated by Django 6.0.2 on 2026-02-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_remove_otp_is_verified_alter_otp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthealthprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
