# Generated by Django 6.0.2 on 2026-02-25 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patienthealthprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreport',
            name='session',
        ),
    ]
