# Generated by Django 6.0.2 on 2026-02-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoruser',
            name='doc_id',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
