# Generated by Django 6.0.2 on 2026-02-26 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctoruser_doc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorViewedPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=100)),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctoruser')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('doctor', 'patient_id')},
            },
        ),
    ]
