# Generated by Django 6.0.2 on 2026-02-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctorviewedpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorviewedpatient',
            name='status',
            field=models.CharField(default='viewed', max_length=20),
        ),
    ]
