# Generated by Django 6.0.2 on 2026-02-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctorviewedpatient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorviewedpatient',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
