# Generated by Django 6.0.2 on 2026-02-27 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctorviewedpatient_symptoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorviewedpatient',
            name='symptoms',
        ),
    ]
