# Generated by Django 6.0.2 on 2026-02-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('symptoms', models.JSONField()),
                ('answers', models.JSONField()),
                ('disease', models.CharField(max_length=200)),
                ('triage', models.IntegerField()),
                ('severity_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
